### ISSUE TITLE
Create models and setup testing environment

### ISSUE THREAD

**Issue by leobz** [leobz/moraki_bank_accounts#2]
## Resume

Create `Accounts` and `Client` models. Setup testing environment with database setup, `Rspec` + `Factory Bot`,  and implement a Basic Inertia Test.

## Tasks
- [x] Create Migrations
- [ ] Setup Testing Environment:
  -  [ ] Setup  test database with docker
  -  [ ] Rspec
  -  [ ] Factory Bot
- [ ] Implement Inertia Test in one endpoint

## Resources
- [inertia-rails testing](https://github.com/inertiajs/inertia-rails?tab=readme-ov-file#testing)
- https://github.com/inertiajs/inertia/issues/1593
