### ISSUE TITLE
Create Accounts CRUD with basic frontend

### ISSUE THREAD

**Issue by leobz** [leobz/moraki_bank_accounts#4]
## Resume
Create Accounts CRUD with a basic frontend, with a main focus in backend validations using autimatized tests

## Tasks
- [x] Create Controllers CRUD Endpoints
- [x] Implement Validations in models
- [x] Create Basic React Views
- [x] Create Inertia Tests for CRUD Endpoints
- [x] Create Inertia Tests for Validations

## Resources:
- [Inertia Rails CSRF Protection](https://github.com/skryukov/inertia_rails-contrib/blob/main/docs/guide/csrf-protection.md)
